<a href="https://colab.research.google.com/github/VARSHITHA-DARMINI/1927_B30_PDS/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

test_scores = np.random.randint(0, 101, size=(4, 4))
print(test_scores)

column_means = np.mean(test_scores, axis=0)
row_means = np.mean(test_scores, axis=1)

print("Column-wise means:", column_means)
print("Row-wise means:", row_means)

std_dev = np.std(test_scores)
variance = np.var(test_scores)

print("Standard Deviation:", std_dev)
print("Variance:", variance)

min_value = np.min(test_scores)
max_value = np.max(test_scores)
min_index = np.argmin(test_scores)
max_index = np.argmax(test_scores)

print("Minimum value:", min_value)
print("Maximum value:", max_value)
print("Index of minimum value:", min_index)
print("Index of maximum value:", max_index)

[[70 25 40 60]
 [24 42 86 83]
 [97 47 48 50]
 [51 43 36 14]]
Column-wise means: [60.5  39.25 52.5  51.75]
Row-wise means: [48.75 58.75 60.5  36.  ]
Standard Deviation: 22.497222050733285
Variance: 506.125
Minimum value: 14
Maximum value: 97
Index of minimum value: 15
Index of maximum value: 8


In [5]:
import numpy as np

rgb_image = np.random.randint(0, 256, size=(3, 3, 3))
print(rgb_image)
red_channel = rgb_image[:, :, 0]
green_channel = rgb_image[:, :, 1]
blue_channel = rgb_image[:, :, 2]

print("Red Channel:\n", red_channel)
print("Green Channel:\n", green_channel)
print("Blue Channel:\n", blue_channel)
red_mean = np.mean(red_channel)
green_mean = np.mean(green_channel)
blue_mean = np.mean(blue_channel)

print(f"Average pixel intensity for Red channel: {red_mean}")
print(f"Average pixel intensity for Green channel: {green_mean}")
print(f"Average pixel intensity for Blue channel: {blue_mean}")
brightness_increase = 50
brightened_image = np.clip(rgb_image + brightness_increase, 0, 255)
print("Brightened Image (clipped at 255):\n", brightened_image)

[[[173  56 107]
  [ 14 138 228]
  [ 66  71 112]]

 [[ 92  43 113]
  [ 18  94 253]
  [228  22  83]]

 [[148  40  84]
  [244  10 181]
  [ 93 111  70]]]
Red Channel:
 [[173  14  66]
 [ 92  18 228]
 [148 244  93]]
Green Channel:
 [[ 56 138  71]
 [ 43  94  22]
 [ 40  10 111]]
Blue Channel:
 [[107 228 112]
 [113 253  83]
 [ 84 181  70]]
Average pixel intensity for Red channel: 119.55555555555556
Average pixel intensity for Green channel: 65.0
Average pixel intensity for Blue channel: 136.77777777777777
Brightened Image (clipped at 255):
 [[[223 106 157]
  [ 64 188 255]
  [116 121 162]]

 [[142  93 163]
  [ 68 144 255]
  [255  72 133]]

 [[198  90 134]
  [255  60 231]
  [143 161 120]]]
